### PR TITLE
Allow derivation result to have arbitrary type

### PR DESCRIPTION
**Pull request by OlegYch**

### CODE REVIEW

**Comment by joroKr21** [comment]
I am surprised that this was so easy.
I also wonder if this solves #61 🤔

**Comment by OlegYch** [comment]
@joroKr21 it's just a fix for `dispatch`, `combine` was already supporting this
this will probably not work for full-auto derivation and recursive classes so doesn't fully address #107

**Comment by OlegYch** [comment]
@joroKr21 i adjusted tests to better show what this enables

**Comment by joroKr21** [comment]
Sure but I can imagine having mutual recursion.
And now we can also have e.g. `CsvColumn` and `CsvRow`.

**Comment by propensive** [comment]
That's interesting. I remember that the type ascription has come and gone a few times, and I thought that we ended up keeping it because it was needed for deriving recursive types... but it was added or removed from both `dispatch` and `combine` in the past; not one of them. A recursive type will need _both_ `combine` and `dispatch`, so I guess that either one of these could have the ascription, and it's sufficient for the typechecker to terminate.

Thanks for the contribution, @OlegYch! I'll make a release now.

**Pull request merged**
