### PR TITLE
Add check that all traits in a hierarchy are sealed

### LINKED ISSUE #243: Check in knownSubclasses that all subtraits are sealed
I'm wondering if we should support the following code:
```
  sealed trait Color7
  trait Color7a extends Color7
  object Color7 {
    case object Red extends Color7a
    case class Custom(rgb: String) extends Color7a
  }
```

By deriving `Color7`, magnolia throws a compilation error:
```
magnolia: could not find any direct subtypes of trait Color7
```
Is it a use-case we should support?

### PR DESCRIPTION
**Pull request by joroKr21**
... and that all classes are final or case classes.
Otherwise the act as an escape hatch (can be extended).'

And make use of `collect`.

Closes #243

### CODE REVIEW

**Comment by kubukoz** [comment]
Are classes also checked to be final?

**Comment by joroKr21** [comment]
> Are classes also checked to be final?

No, but I think they should be checked for being either final or case classes.

**Comment by joroKr21** [comment]
@propensive the build is green although tests are not passing.
Also the tests don't run on Scala 2.13 🤔

**Comment by propensive** [comment]
I'll fix the problem with the tests soon, when I move to Github Actions.

**Comment by propensive** [comment]
Also I approved (looks solid) though will wait until that last test actually passes before merging. ;)

**Comment by joroKr21** [comment]
> Also I approved (looks solid) though will wait until that last test actually passes before merging. ;)

Done ✅

**Pull request merged**
