### PR TITLE
Cross-build for Scala Native

### LINKED ISSUE #36: Support Scala Native
It would be nice if Magnolia worked on Scala Native. Anyone familiar with setting up Scala Native in SBT could probably tackle this.

### PR DESCRIPTION
**Pull request by jodersky**
Also add a simple travis build config and compile magnolia for Scala 2.13.0-M3.

Closes #36

### CODE REVIEW

**Comment by jodersky** [comment]
The travis build status is available here https://travis-ci.org/jodersky/magnolia

**Comment by propensive** [comment]
I just instructed Sonatype to publish it, so all being well, v0.7.1 should be available soon!

**Comment by jodersky** [comment]
Sweet, thanks! I'm really bad at remembering publishing steps in sbt too, so I set up an automated script on most of my projects that publishes to sonatype when a release is pushed. https://github.com/drivergroup/spray-json-derivation/blob/475f6f6/.ci/build. Let me know if you'd like any help setting up something similar.

**Comment by propensive** [comment]
I would be interested in exploring that! @fommil has reported some problems with `+publishSigned` in the last couple of days (which I'm planning to look at some time, on several projects). `sonatypeRelease` has never worked for me, but I think the reason is that I never gave it my credentials anywhere...

Will you be coming to NE Scala in Boston next week?

**Pull request merged**
