### PR TITLE
enable derivation of case class with private constructors

### PR DESCRIPTION
**Pull request by yanns**
https://github.com/propensive/magnolia/issues/138#issuecomment-536532038

### CODE REVIEW

**Comment by yanns** [comment]
Part of my effort to port our serialization/deserialization libraries to use magnolia: https://github.com/sphereio/sphere-scala-libs/tree/derive_with_magnolia

**Comment by yanns** [comment]
@jto this is a revert of https://github.com/propensive/magnolia/pull/139 to enable derivation where the private constructor is accessible.

If I try to derive the type class instance where the private constructor is not accessible, scalac throws a compilation error:
```
/tests.scala:246:15: constructor PrivateCons in class PrivateCons cannot be accessed in <$anon: magnolia.CaseClass[magnolia.examples.Show.Typeclass,magnolia.tests.PrivateCons]>
[error]       Show.gen[PrivateCons].show(PrivateCons("dada", "phil"))
[error]               ^
```
The compilation error is expected, and I found the error message friendly enough to understand what is going on.

@propensive any thoughts about this PR?

**Comment by jto** [comment]
Merged it since no one commented

**Comment by aeons** [comment]
Could we also have a release with this change? :)

**Comment by jto** [comment]
I don't have the permissions to publish a release. Ping @propensive :)

**Pull request merged**
