### PR TITLE
Refactor Derivation interface

### PR DESCRIPTION
**Pull request by OlegYch**
Move implementation out of Derivation for easier reuse in case a different interface is needed

### CODE REVIEW

**Comment by OlegYch** [comment]
@adamw can this be released please?

**Comment by adamw** [comment]
@OlegYch sorry for the delay. I'm hesitant as this would increase the surface area of binary compatibility that we have to maintain quite significantly (as it would include the inline method implementations).

**Comment by OlegYch** [comment]
@adamw i agree, but these are methods already exposed in public api, just packaged in a more a reusable way

**Comment by adamw** [comment]
You are right, it's already public :) I've adjusted the naming abit, let me know what you think

**Comment by OlegYch** [comment]
@adamw naming changes look good, but promoting type member to type parameter makes it less flexible and wouldn't work for my specific usecase (sample here https://github.com/softwaremill/magnolia/issues/242 )

**Comment by adamw** [comment]
@OlegYch now? :)

**Comment by OlegYch** [comment]
@adamw LGTM

**Comment by adamw** [comment]
Should be released soon :)

**Pull request merged**
