### PR TITLE
Add minimal testcase for testing functor derivation.

### PR DESCRIPTION
**Pull request by LukaJCB**
As requested :)

The Functor type class should be something like 
```scala
trait Functor[F[_]] {
  def map[A, B](fa: F[A])(f: A => B): F[B]
}
```

and the manual instance would look something like this:
```scala

implicit val functorTree: Functor[Tree] = new Functor[Tree] {
  def map[A, B](fa: Tree[A])(f: A => B): Tree[B] = fa match {
    case Leaf(a) => Leaf(f(a))
    case Branch(left, right) => Branch(map(left)(f), map(right)(f))
  }
}
```

### CODE REVIEW

**Comment by propensive** [comment]
Ok, let's give this a go!

**Comment by propensive** [comment]
I'm not sure I'm making much progress with this. I think it will require some more changes to Magnolia, and I'm not currently sure what they are...

**Comment by propensive** [comment]
I've postponed trying to find a solution to this until after the 1.0 release.

**Comment by propensive** [comment]
I wonder whether we might be closer to implementing this once I've finished implementing #46. I think it's likely to be a step closer, so I'll keep this PR open until that's merged.

**Comment by LukaJCB** [comment]
I'm going to close this for now :)

**Pull request closed without merging**
